// <auto-generated />
using System;
using Messenger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Messenger.Migrations
{
    [DbContext(typeof(MessengerContext))]
    [Migration("20211215034352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("pgcrypto")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Messenger.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msg");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent");

                    b.Property<string>("Un")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("un");

                    b.HasKey("Id");

                    b.HasIndex("Un");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Messenger.Models.User", b =>
                {
                    b.Property<string>("Un")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("un");

                    b.Property<string>("Pw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pw");

                    b.HasKey("Un")
                        .HasName("users_pk");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Messenger.Models.Message", b =>
                {
                    b.HasOne("Messenger.Models.User", "UnNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("Un")
                        .HasConstraintName("messages_fk")
                        .IsRequired();

                    b.Navigation("UnNavigation");
                });

            modelBuilder.Entity("Messenger.Models.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
